### PR TITLE
Update ffi and update markets to v9

### PR DESCRIPTION
**Pull request by geoff-vball**
Note: Currently pointing at a dangling commit of go-state-types.

Updates markets to v9 which is required for the nv17 upgrade in lotus.

### CODE REVIEW

**Review by arajasek — APPROVED** [review]

**Comment by arajasek** [comment]
Let's merge this and tag it as v1.24.1-rc1. This will be for the Filecoin network v17 upgrade.

**Comment by hannahhoward** [comment]
@arajasek I'm late to this party but we have some pending features branches we'd like to release pre-v17 upgrade, for boost and filclient.

can we speak one on one about what we plan to do here? (given impending deprecations to be announced -- cc @jennijuju )

**Comment by jennijuju** [comment]
> @arajasek I'm late to this party but we have some pending features branches we'd like to release pre-v17 upgrade, for boost and filclient.
> 
> can we speak one on one about what we plan to do here? (given impending deprecations to be announced -- cc @jennijuju )

unfortunately id like to avoid that
https://filecoinproject.slack.com/archives/CP50PPW2X/p1663707244492419

**Comment by jennijuju** [comment]
@hannahhoward tho we can test v1.12.4 in lotus nov feature release

**Comment by hannahhoward** [comment]
ok -- let's make 1.24.1 or 1.24.0-v17 a LOTUS nv17 ONLY release (no new features). Then we can ship a 1.25.0 on top of that into boost with new features included. If Lotus discovers later there was something wrong with v1.24.1, we can branch additional changes off 1.24.1 to make 1.24.2 and so on, then merge them into master to mantain a unified commit history.

The only delta for you all is if you have to make additional changes to support NV17, you branch of 1.24.1 to avoid receiving new features that you probably don't want to ship with the network upgrade.

Also, with upcoming deprecation plans, it probably makes sense for Lotus to have its own maintainence branch any way.

sound good @jennijuju?

**Comment by jennijuju** [comment]
I’m not too sure - cuz as long as we are supporting lotus client, we might want to keep update on some of the gfm changes. I need to think about it more! But the nv17 branch stuff sgtm, thank you for understanding (in retrospect I should’ve tagged you in that thread sorry for the oversight!

**Pull request merged**
