### PR TITLE
use addresses from miner info for connecting to miners

### PR DESCRIPTION
**Pull request by whyrusleeping**
Not quite complete as i havent gotten the tests to pass yet, but this is most of the work.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@hannahhoward i'm not exactly sure what the right way to get tests passing here is, any thoughts?

**Comment by hannahhoward** [comment]
@whyrusleeping submitted PR to this branch to get tests to pass. Note: this does not make the integration tests actually test the functionality you've implemented. To do that you'd need to actually configure the libp2p mocknet.

**Comment by hannahhoward** [comment]
Another question: in this scenario, is the miner running seperate `lotus-storage-miner` processes with a seperate store for tracking deal progress? If not there are some potential complications: when a storage provider is initiatilzed, it attempts to restart processing of deals in progress when it was shut down. So we may need to add a parameter to StorageProvider.Start that specifies whether or not to restart deals -- and only make that value true on one of the lotus-storage-miner processes.

**Comment by ribasushi** [comment]
@whyrusleeping @magik6k this is somewhat blocking us to test an end-ot-end offline deal with dumbodrop. Is there something preventing a merge this week?

/cc @mikeal

**Comment by hannahhoward** [comment]
@ribasushi I was waiting for @whyrusleeping to merge #291 which gets test passing. I am going to assume he's got other things happening and I'll take this home today.

**Comment by hannahhoward** [comment]
@ribasushi this is ready for merge now from my point of view, but I don't know if you want to get confirmation from @whyrusleeping or @magik6k

**Comment by hannahhoward** [comment]
(I went ahead and did the rebase)

**Pull request merged**
