### PR TITLE
FIP 0027 integration

### PR DESCRIPTION
**Pull request by arajasek**
Integrates [a change to FIP-0027](https://github.com/filecoin-project/FIPs/pull/318). o

### CODE REVIEW

**Comment by ZenGround0** [comment]
@arajasek I can't tag you for it but need your review here

**Comment by ZenGround0** [comment]
`TestRestartOnlyProviderDataTransfer` appears to be flaky

**Comment by arajasek** [comment]
Approve to all of @ZenGround0's commits! If someone can review the first commit and green check this, we can merge!

**Review by dirkmc — APPROVED** [review]
I'm approving this PR but I do have one non-blocking question.
There is a commented out test in [storagemarket/impl/providerstates/provider_states_test.go](https://github.com/filecoin-project/go-fil-markets/pull/694/files#diff-030eebc7b798e04df2570151bf91a20d462a2536cb40a5161d5bb5ba0fffa62f).
Why is this test commented out? If it's no longer relevant let's remove it.

**Comment by ZenGround0** [comment]
> There is a commented out test in [storagemarket/impl/providerstates/provider_states_test.go](https://github.com/filecoin-project/go-fil-markets/pull/694/files#diff-030eebc7b798e04df2570151bf91a20d462a2536cb40a5161d5bb5ba0fffa62f).
Why is this test commented out? If it's no longer relevant let's remove it.

Thanks, this test is made irrelevant by the new label type which forbids invalidly long labels at the type level.  Removing.

**Pull request merged**
