### PR TITLE
Increase another exceptionally tight test timeout

### PR DESCRIPTION
**Pull request by ribasushi**

### CODE REVIEW

**Review by whyrusleeping — COMMENTED** [review]
ci still red yo

**Comment by ribasushi** [comment]
yeah, apparently even more timeouts, looking...

**Comment by ribasushi** [comment]
I'll close this one, another pass is needed, too many short-waits :(

**Comment by ribasushi** [comment]
Opened https://github.com/filecoin-project/go-fil-markets/issues/589#issue-951953109 instead, we'll circle back to it at some stage.

**Pull request closed without merging**
