### PR TITLE
support padding out smaller files

### PR DESCRIPTION
**Pull request by whyrusleeping**
This allows me to take a 1MB file, pad it up to 512MB, and make a deal with a miner whose minimum piece size is 512MB

### CODE REVIEW

**Review by ribasushi — APPROVED** [review]
I built a stock v1.6.0 with the following modification:
- cherry-pick https://github.com/filecoin-project/lotus/pull/5988/commits/cbe9bc316c2b9
```
diff --git a/go.mod b/go.mod
index 503e95c5d..2d2548ccc 100644
--- a/go.mod
+++ b/go.mod
@@ -31 +31 @@ require (
-       github.com/filecoin-project/go-commp-utils v0.0.0-20201119054358-b88f7a96a434
+       github.com/filecoin-project/go-commp-utils v0.1.1-0.20210407220142-9d7f7aaf8c9c
@@ -35 +35 @@ require (
-       github.com/filecoin-project/go-fil-markets v1.1.9
+       github.com/filecoin-project/go-fil-markets v1.1.10-0.20210407195421-65658e33ed64
```

🎉 OMG IT WORKED 🎉

Retrieval from a completely unrelated **UNPATCHED** client worked too

@whyrusleeping you are the hero we **have** but do not deserve

:shipit: ( of course port 65658e3 back from https://github.com/filecoin-project/go-fil-markets/pull/537 )

**Comment by ribasushi** [comment]
@whyrusleeping we never shipped this way back for some reason: I merged it with latest master and made extra changes - please review / ack.

I particularly dislike `Inflator` thing, but can't come up with a better way. See https://github.com/filecoin-project/lotus/pull/6683#issue-683917919 for context.

**Comment by ribasushi** [comment]
@whyrusleeping ok, the original thing that you wrtoe has been reviewed and good
I have added the following on top, please look over when time permits
image

**Comment by ribasushi** [comment]
I *can not* reproduce this CI fail locally no matter what I do :(

**Comment by whyrusleeping** [comment]
Okay, that looks good to me.

**Pull request merged**
