### PR TITLE
Update specs-actors and cbor-gen

### PR DESCRIPTION
**Pull request by Stebalien**
Depends on https://github.com/filecoin-project/go-data-transfer/pull/64.

### CODE REVIEW

**Comment by Stebalien** [comment]
I don't know why I needed to regenerate the docs, but anything to get the tests to pass...

**Comment by Stebalien** [comment]
Back to draft due to a go-address bug.

**Comment by hannahhoward** [comment]
@Stebalien please ignore docs errors. It's a bug I need to address

**Comment by Stebalien** [comment]
This test keeps flip-flopping from StorageDealProviderFunding to StorageDealEnsureProviderFunds.

https://github.com/filecoin-project/go-fil-markets/blob/46d037bd26316d58e13edc9a4e85af16358993a5/storagemarket/integration_test.go#L282

**Pull request merged**
