### PR TITLE
Retry with exponential backoff for stream opening

### PR DESCRIPTION
**Pull request by aarshkshah1992**
Closes https://github.com/filecoin-project/lotus/issues/3416.

@hannahhoward Should we do this for the retrieval market as well ?

### CODE REVIEW

**Comment by hannahhoward** [comment]
make sure to fix lint errors before merge

**Comment by aarshkshah1992** [comment]
@hannahhoward On it.

**Comment by aarshkshah1992** [comment]
@hannahhoward 

1. There was a very deep bug in the test wherein because of using randomly generated temporary file paths, we werent being to find the piece file across restarts. Have fixed that bug now and the tests look good on repeated runs.

2. Have added the backoff-retry logic for the retrieval markets as well.

**Comment by hannahhoward** [comment]
@aarshkshah1992 this great but it looks like you still have lint and test failures. At least one of the test failures looks non-flaky and needs a change. (TestProviderStop)

**Comment by aarshkshah1992** [comment]
@hannahhoward Fixed the linting issue and test. Please take a look.

**Review by hannahhoward — APPROVED** [review]

**Pull request merged**
